FROM vllm/vllm-openai:latest

WORKDIR /workspace

COPY ./requirements.txt .
RUN pip install -r requirements.txt

CMD ["jupyter", "notebook", "--ip=0.0.0.0", "--port=8888", "--no-browser", "--allow-root", "--NotebookApp.token=''", "--notebook-dir=/workspace"]
