services:
  ice-cream-translator:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: ice_cream_container
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu, compute, utility]
    environment:
      - HF_HOME=/workspace/models/cache
      - TOKENIZERS_PARALLELISM=true
    ports:
      - "8000:8000"
    ipc: host